Basic taproot BIP32 derivation & keyspend support
diybitcoinhardware/embit pull request #33
Opened 2022-08-10 17:02 UTC by kdmukai

* Adds basic support for the BIP-371 Taproot psbt field `PSBT_IN_TAP_BIP32_DERIVATION` to properly parse bip32 derivations in Taproot psbts.
* Only supports the root ("internal") key and raises an error if a key within a leaf is provided.
* Updates Taproot psbt signing to expect X-only pubkeys.
* Updates test cases to test that bip32 derivation was successful and fixes so that the X-only pubkeys expectation passes.

---

Note: I believe that the change to expect X-only pubkeys will break the existing Specter-DIY + Specter Desktop workaround. I opted to not include transition code (test for X-only pubkey and normal pubkey) to keep these changes as clean as possible. But I can add that in with a "`TODO: remove this later`" reminder or something.

I will also try to make a PR to update Specter Desktop to output the `0x16` and `0x17` BIP-371 fields. Once that's done, a breaking change to pull both Specter Desktop and Specter-DIY into compliance could be done in tandem.

---

TODO:
`test_psbtview.PSBTTest` is failing on `test_sign`:
```
FAIL: test_sign (tests.test_psbtview.PSBTTest)
Test if we can sign psbtview and get the same as from signing psbt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kdmukai/dev/embit/tests/tests/test_psbtview.py", line 113, in test_sign
    self.assertEqual(ser.getvalue(), psbt.serialize())
AssertionError: b'psb[844 chars]0\x00"\x02\x02\xa9\x81\xb3?~\xb9*\n\xcf77P\x92[890 chars]\x00' != b'psb[844 chars]0\x00\x01\x01\x1f\x80\x96\x98\x00\x00\x00\x00\[2246 chars]\x00'
```
This failure pre-dates these changes so something was either already broken or something is off with my local setup.

2022-08-11 14:12 UTC, kdmukai commented
FYI - still making improvements and tweaks so this PR should be considered DRAFT (but I don't seem to have permissions to revert the PR status to DRAFT).

2022-08-11 14:46 UTC, stepansnigirev commented
Converted to draft

2022-08-27 09:01 UTC, stepansnigirev requested changes
PSBT parsing should not fail if the library can't sign - maybe it's not used for signing at all. You can raise when signing, but I'd better ignore inputs we don't know how to sign.
For example, when you try to sign PSBT transaction with a wrong key it doesn't raise an error, it just returns 0 as a number of added signatures. I think for tap leafs we should do the same.

2022-08-27 09:01 UTC, stepansnigirev commented on src/embit/psbt.py
> +        # tuples of (num_leaf_hashes, [leaf_hashes], DerivationPath)
Why do you need `num_leaf_hashes` in this tuple if you could just do `len(leaf_hashes)`?

2022-08-27 09:01 UTC, stepansnigirev commented on src/embit/psbt.py
> +                    raise PSBTError("Signing for public keys in leaves not yet implemented")
I don't think you want to raise this error here - it's not signing, it's just parsing.
I suggest parsing PSBT without failing, and raise an error when singing, or maybe even ignore input that we don't know how to sign without raising errors.

2022-08-27 09:01 UTC, stepansnigirev commented on tests/tests/test_psbtview.py
> +                print(b64)
I don't think it's necessary

2022-08-29 21:24 UTC, kdmukai commented on tests/tests/test_psbtview.py
> +                print(b64)
Leftover artifact of my debugging. Removed.

2022-08-29 21:24 UTC, kdmukai commented on src/embit/psbt.py
> +        # tuples of (num_leaf_hashes, [leaf_hashes], DerivationPath)
Just being too literal in my thinking! Removed with matching changes elsewhere.

2022-08-29 21:25 UTC, kdmukai commented on src/embit/psbt.py
> +                    raise PSBTError("Signing for public keys in leaves not yet implemented")
Removed these exceptions for parsing and for signing.

2022-10-09 18:59 UTC, stepansnigirev approved these changes

2022-10-14 10:29 UTC, merged